apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
  namespace: fcg-apps
  labels:
    app: users-api
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  RUN_DB_MIGRATIONS_ON_STARTUP: "true"
  Queues__Users__Commands: "users.commands"
  Queues__Users__Events: "users.events"
  Queues__Catalog__Commands: "catalog.commands"
  Queues__Catalog__Events: "catalog.events"
  Queues__Payments__Commands: "payments.commands"
  Queues__Payments__Events: "payments.events"
  Queues__Notifications__Commands: "notifications.commands"
  Queues__Notifications__Events: "notifications.events"
  RabbitMq__HostName: "rabbitmq-service.fcg-infra.svc.cluster.local"
  Loki__Url: "http://loki-service.fcg-infra.svc.cluster.local:3100"
  Jwt__Issuer: "cloud-games"
  Jwt__Audience: "cloud-games-audience"
  Jwt__ExpiryMinutes: "60"


